export const CollectionActionTypes = {
    FETCH_COLLECTION_START: "SET_COLLECTION_START",
    FETCH_COLLECTION_SUCCESS: 'SET_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
  };